# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package verify --file pom.xml
      env: 
        GENERATE_TOKEN: ${{secrets.GENERATE_TOKEN}}
        MYSQL_HOST: ${{secrets.MYSQL_HOST}}
        MYSQL_PORT: ${{secrets.MYSQL_PORT}}
        MYSQL_DB: ${{secrets.MYSQL_DB}}
        MYSQL_USERNAME: ${{secrets.MYSQL_USERNAME}}
        MYSQL_PWD: ${{secrets.MYSQL_PWD}}
